FROM ubuntu

RUN apt-get remove python* \
    apt-get install python3.6 && python2.7 \
    ln -s /usr/bin/python3.6 /usr/bin/python3 \
    ln -s /usr/bin/python2.7 /usr/bin/python \

# Install dependencies needed for building and running OpenCV
RUN apt-get update && apt-get install -y --no-install-recommends \
    # to build and install
    unzip wget git \
    build-essential cmake pkg-config \
    # to work with images
    libjpeg-dev libtiff-dev libpng-dev \
    # to work with videos
    libavcodec-dev libavformat-dev libswscale-dev libv4l-dev \
    # needed by highgui tool
    libgtk2.0-dev \
    # for opencv math operations
    libatlas-base-dev gfortran \
    # others
    libtbb2 libtbb-dev python-pip python2.7-dev python3-pip python3.6-dev \
    # cleanup
    && rm -rf /var/lib/apt/lists/* \
    && apt-get -y autoremove

# Install python packages
RUN pip install --no-cache-dir \
    # OpenCV dependency
    setuptools numpy \
    # other usefull stuff
    # ipython \
    # cleanup
    && find /usr/local \
       \( -type d -a -name test -o -name tests \) \
       -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
       -exec rm -rf '{}' + \
    && cd / \
    && rm -rf /usr/src/python ~/.cache

# Install python3 packages
RUN pip3 install --no-cache-dir \
    # OpenCV dependency
    setuptools numpy \
    # other usefull stuff
    # ipython \
    # cleanup
    && find /usr/local \
       \( -type d -a -name test -o -name tests \) \
       -o \( -type f -a -name '*.pyc' -o -name '*.pyo' \) \
       -exec rm -rf '{}' + \
    && cd / \
    && rm -rf /usr/src/python ~/.cache

# Install OpenCV
COPY download_build_install_opencv.sh download_build_install_opencv.sh
RUN bash download_build_install_opencv.sh
